export const hospitalType = [
  "Cancer Hospital",
  "Research Hospital",
  "Private Hospital",
  "Government Hospital",
  "Maternity Hospital",
  "Trauma Center",
  "Children’s Hospital",
] as const

export const departments = [
  "Emergency Department (ER)",
  "Cardiology",
  "Neurology",
  "Oncology",
  "Orthopedics",
  "Pediatrics",
  "Gynecology/Obstetrics",
  "Radiology",
  "Surgery (General Surgery)",
  "Intensive Care Unit (ICU)",
  "Neonatology (NICU)",
  "Dermatology",
  "Urology",
  "Gastroenterology",
  "Anesthesiology",
  "Ophthalmology",
  "Otolaryngology (ENT)",
  "Endocrinology",
  "Psychiatry",
  "Pulmonology",
  "Nephrology",
  "Rheumatology",
  "Pathology",
  "Hematology",
  "Physical Therapy/Rehabilitation",
]

export const services = [
  "Emergency Care",
  "Outpatient Services",
  "Surgery",
  "Maternity Services",
  "Pediatrics",
  "Radiology & Imaging",
  "Laboratory Services",
  "Cardiology",
  "Oncology",
  "Physiotherapy",
  "Dermatology",
  "Neurology",
  "Orthopedics",
  "Pharmacy",
  "Dialysis",
  "Mental Health Services",
  "ICU (Intensive Care Unit)",
  "Dental Services",
  "Eye Care",
  "Rehabilitation Services",
  "Blood Bank",
  "Gastroenterology",
  "Endocrinology",
  "Respiratory Services",
  "Vaccination Services",
  "Nutrition & Dietetics",
  "Palliative Care",
  "Home Healthcare",
  "Chronic Disease Management",
  "Telemedicine",
]
