export const hospitalType = [
  "Cancer Hospital",
  "Research Hospital",
  "Clinic",
  "Private Hospital",
  "Government Hospital",
  "Maternity Hospital",
  "Trauma Center",
  "Children’s Hospital",
] as const

export const departments = [
  "Emergency Department (ER)",
  "Cardiology",
  "Neurology",
  "Oncology",
  "Orthopedics",
  "Pediatrics",
  "Gynecology/Obstetrics",
  "Radiology",
  "Surgery (General Surgery)",
  "Intensive Care Unit (ICU)",
  "Neonatology (NICU)",
  "Dermatology",
  "Urology",
  "Gastroenterology",
  "Anesthesiology",
  "Ophthalmology",
  "Otolaryngology (ENT)",
  "Endocrinology",
  "Psychiatry",
  "Pulmonology",
  "Nephrology",
  "Rheumatology",
  "Pathology",
  "Hematology",
  "Physical Therapy/Rehabilitation",
]
